### ISSUE TITLE
Tertiary node on bending binary yielding error

### ISSUE THREAD

**Issue by modelint** [modelint/flatland-model-diagram-editor#40]
Error:
`Traceback (most recent call last):
  File "/Users/leonstarr/SDEV/Python/Environments/TF1/bin/flatland", line 8, in <module>
    sys.exit(main())
  File "/Users/leonstarr/SDEV/Python/Environments/TF1/lib/python3.9/site-packages/flatland/__main__.py", line 104, in main
    class_diagram = XumlClassDiagram(
  File "/Users/leonstarr/SDEV/Python/Environments/TF1/lib/python3.9/site-packages/flatland/xuml/xuml_classdiagram.py", line 87, in __init__
    self.draw_association(rnum=rnum, association=r, binary_layout=rlayout)
  File "/Users/leonstarr/SDEV/Python/Environments/TF1/lib/python3.9/site-packages/flatland/xuml/xuml_classdiagram.py", line 187, in draw_association
    a_stem = New_Stem(stem_type='associative mult', semantic=association['assoc_mult'] + ' mult',
KeyError: 'assoc_mult'`

![image](https://user-images.githubusercontent.com/1711000/111895546-99b65b80-89d0-11eb-807b-0e4d4076839e.png)

**Comment by modelint** [comment]
Problem went away mysteriously.  Will do further diagnostics so leaving this open for now.

**Comment by modelint** [comment]
Should be resolved by some fixes and updated error reporting.
