### ISSUE TITLE
Same class node specified twice in model file, cell occupied error

### ISSUE THREAD

**Issue by modelint** [modelint/flatland-model-diagram-editor#67]
When an xmm file duplicates a class node (by mistake), it leads to a cryptic CellOccupiedFE error
when only one placement is specified in the layout.  Need a better way to handle the diagnostic

`(TF1) [552] !!
flatland -G -m event-action-subsystem.xmm -l event-action-subsystem.mls -d event-action-subsystem-diagram.pdf
Flatland: ERROR - Single cell node overlap at [1, 1]
Traceback (most recent call last):
  File "/Users/starr/SDEV/Environments/TF1/bin/flatland", line 8, in <module>
    sys.exit(main())
  File "/Users/starr/SDEV/Environments/TF1/lib/python3.9/site-packages/flatland/__main__.py", line 150, in main
    class_diagram = XumlClassDiagram(
  File "/Users/starr/SDEV/Environments/TF1/lib/python3.9/site-packages/flatland/xuml/xuml_classdiagram.py", line 77, in __init__
    self.nodes = self.draw_classes()
  File "/Users/starr/SDEV/Environments/TF1/lib/python3.9/site-packages/flatland/xuml/xuml_classdiagram.py", line 193, in draw_classes
    nodes[node_name] = SingleCellNode(
  File "/Users/starr/SDEV/Environments/TF1/lib/python3.9/site-packages/flatland/node_subsystem/single_cell_node.py", line 43, in __init__
    self.Grid.place_single_cell_node(node=self)
  File "/Users/starr/SDEV/Environments/TF1/lib/python3.9/site-packages/flatland/node_subsystem/grid.py", line 334, in place_single_cell_node
    raise CellOccupiedFE
flatland.flatland_exceptions.CellOccupiedFE
`

**Comment by modelint** [comment]
On second thought, it seems that this is a model error, specific to xUML.  So the model processor should look for duplicates and flag the error before trying to draw the same node twice in a cell
